### ISSUE TITLE
Deploy EUR/USD pool

### ISSUE THREAD

**Issue by mynameuhh** [tracer-protocol/perpetual-pools-contracts#241]
As per: https://snapshot.org/#/tracer.eth/proposal/0xd64527f49f1a084fee15e3d0d832ebe14370cc8dadc20cbe947287f5697a6399

- [x] Deploy OracleWrapper
- [x] Make sure marketing team is synced
- [x] Deploy pool via multisig 
    - [x] Deploy pool via multisig on TestNet #246 
    - [x] Deploy pool via multisig on Aribtrum One

**Comment by sporejack** [comment]
> Deploy `OracleWrapper`

For the new price feed, correct?

**Comment by mynameuhh** [comment]
Yep @sporejack

**Comment by nisdo** [comment]
V1 deployment not blocked as we can use an old branch of V1 to do the deployment

**Comment by nisdo** [comment]
Hey @mynameuhh just to clarify the checkboxes above, do they align to specific subtasks currently active? if so, can we edit the checklist to have direct hyperlinks on them?
